name = "quake-map-web"
compatibility_date = "2025-09-06"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "build"

[env.development]
name = "quake-map-web-dev"

[env.development.vars]
API_URL = "https://quake-map-dev.your-subdomain.workers.dev"

[env.production]
name = "quake-map-web"

[env.production.vars]
API_URL = "https://quake-map.your-subdomain.workers.dev"
