name = "quake-map-api"
main = "src/index.ts"
compatibility_date = "2025-09-06"
compatibility_flags = ["nodejs_compat"]

# Enable logging
[observability]
enabled = true

[env.development]
name = "quake-map-api-dev"

[env.development.vars]
ENVIRONMENT = "development"
PROJECT_NAME = "QuakeMap API Dev"
USGS_API_URL = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary"
CORS_ORIGINS = "http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,https://quake-map-web-dev.ivanmaierg99.workers.dev"

[env.production]
name = "quake-map-api"

[env.production.vars]
ENVIRONMENT = "production"
PROJECT_NAME = "QuakeMap API"
USGS_API_URL = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary"
CORS_ORIGINS = "https://quake-map-web-dev.ivanmaierg99.workers.dev,https://quake-map-web.ivanmaierg99.workers.dev"
